Setup default stdout to utf-8
Error occurred when Linux Language environment variables  is set to "zh_CN.UTF-8":
File "/usr/local/lib/python3.6/dist-packages/gpustat/core.py", line 397, in print_to
    fp.write(''.join(reps))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 61: ordinal not in range(128)